# Generated by Django 4.2.4 on 2024-09-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="text",
            new_name="question",
        ),
    ]
