# Generated by Django 4.2.4 on 2024-09-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rooms', '0001_initial'),
        ('chat_messages', '0002_rename_question_message_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_rooms.chatroom'),
        ),
    ]
